### ISSUE TITLE
Rejecting login on a session where login failed

### ISSUE THREAD

**Issue by johnjelinek** [terraform-providers/terraform-provider-vsphere#537]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.21.0
+ provider.infoblox (unversioned)
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.vsphere v1.6.0
```

### vSphere Provider Version

```
.
├── provider.aws
├── provider.infoblox
├── provider.vsphere ~> 1.6.0
├── module.prometheus-aws-server
│   ├── provider.aws (inherited)
│   ├── provider.null
│   ├── provider.terraform
│   └── module.ec2-private
│       ├── provider.aws (inherited)
│       └── provider.template
└── module.prometheus-dev-server
    ├── provider.infoblox (inherited)
    ├── provider.null
    └── provider.vsphere (inherited)
```

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data "vsphere_datacenter" "dc" {
  name = "${var.vsphere_datacenter}"
}

data "vsphere_datastore" "datastore" {
  name = "${var.vsphere_datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name = "${var.vsphere_resource_pool}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name = "${var.vm_vlan}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name = "base"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "prometheus" {
  name = "${var.vm_hostname}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 4
  memory = 16384
  guest_id = "centos64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    name = "${var.vm_hostname}.vmdk"
    size = 40
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${var.vm_hostname}"
      }

      network_interface {
        ipv4_address = "${var.vm_ip_address}"
        ipv4_netmask = 24
      }

      ipv4_gateway = "${var.vm_ip_gateway}"
    }
  }
}
```

### Debug Output

```
...snippet...
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] DiskRefreshOperation: Looking for devices known in state
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] diskPathOrName: Using defined path value "dfw-sbx-prom-1/dfw-sbx-prom-1.vmdk"
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] disk.0 (key 2000 at scsi:0:0) (dfw-sbx-prom-1/dfw-sbx-prom-1.vmdk): Reading state
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] diskPathOrName: Using defined path value "dfw-sbx-prom-1/dfw-sbx-prom-1.vmdk"
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] disk.0 (key 2000 at scsi:0:0) (dfw-sbx-prom-1/dfw-sbx-prom-1.vmdk): Read finished (key and device address may have changed)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] DiskRefreshOperation: Resource set to write after known device search: (key 2000at scsi:0:0)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] DiskRefreshOperation: Probable orphaned disk devices:
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] DiskRefreshOperation: Adding orphaned devices
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] DiskRefreshOperation: Resource set to write after adding orphaned devices: (key 2000 at scsi:0:0)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] DiskRefreshOperation: Final (sorted) resource set to write: (key 2000 at scsi:0:0)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] DiskRefreshOperation: Refresh operation complete, sending new resource set
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Beginning refresh
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Network devices located: ethernet-0
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Current resource set from state: (key 4000 at pci:0:7)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: 1 devices over a 1 unit range
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Looking for freshly-created resources to read in
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Network devices after freshly-created device search: ethernet-0
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Resource set to write after freshly-created device search: (<nil>)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Looking for devices known in state
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] network_interface.0 (key 4000 at pci:0:7): Reading state
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] FindVirtualDevice: Looking for device with key 4000
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] FindVirtualDevice: Device found: ethernet-0
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] network_interface.0 (key 4000 at pci:0:7): Read finished (key and device addressmay have changed)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Resource set to write after known device search: (key 4000 at pci:0:7)
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Probable orphaned network interfaces:
2018-05-31T11:29:45.149-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Adding orphaned devices
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Resource set to write after adding orphaned devices: (key 4000 at pci:0:7)
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] NetworkInterfaceRefreshOperation: Refresh operation complete, sending new resource set
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Beginning refresh
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: CDROM devices located:
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Current resource set from state:
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Looking for freshly-created resources to read in
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: CDROM devices after freshly-created device search:
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Resource set to write after freshly-created device search:
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Looking for devices known in state
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Resource set to write after known device search:
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Probable orphaned CDROM devices:
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Resource set to write after adding orphaned devices:
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] CdromRefreshOperation: Refresh operation complete, sending new resource set
2018-05-31T11:29:45.150-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] Reading tags for object "vm-3081"
2018-05-31T11:29:45.303-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: 2018/05/31 11:29:45 [DEBUG] Tags for object "vm-3081":
2018/05/31 11:29:45 [ERROR] root.prometheus-dev-server: eval: *terraform.EvalRefresh, err: vsphere_virtual_machine.prometheus: Get unexpected status code: 500: call failed: Error response from vCloud Suite API: {"value":{"messages":[{"id":"vapi.bindings.method.impl.unexpected","default_message":"Provider method implementation threw unexpected exception: Rejecting login on a session where login failed","args":["Rejecting login on a session where login failed"]}]},"type":"com.vmware.vapi.std.errors.internal_server_error"}
2018/05/31 11:29:45 [ERROR] root.prometheus-dev-server: eval: *terraform.EvalSequence, err: vsphere_virtual_machine.prometheus: Get unexpected status code: 500: call failed: Error response from vCloud Suite API: {"value":{"messages":[{"id":"vapi.bindings.method.impl.unexpected","default_message":"Provider method implementation threw unexpected exception: Rejecting login on a session where login failed","args":["Rejecting login on a session where login failed"]}]},"type":"com.vmware.vapi.std.errors.internal_server_error"}
2018/05/31 11:29:45 [TRACE] [walkRefresh] Exiting eval tree: module.prometheus-dev-server.vsphere_virtual_machine.prometheus
2018/05/31 11:29:45 [TRACE] dag/walk: upstream errored, not walking "provider.vsphere (close)"
...snippet...
Error: Error refreshing state: 1 error(s) occurred:

* module.prometheus-dev-server.vsphere_virtual_machine.prometheus: 1 error(s) occurred:

* module.prometheus-dev-server.vsphere_virtual_machine.prometheus: vsphere_virtual_machine.prometheus: Get unexpected status code: 500: call failed: Error response from vCloud Suite API: {"value":{"messages":[{"id":"vapi.bindings.method.impl.unexpected","default_message":"Provider method implementation threw unexpected exception: Rejecting login on a session where login failed","args":["Rejecting login on a session where login failed"]}]},"type":"com.vmware.vapi.std.errors.internal_server_error"}
```

### Expected Behavior

Should refresh the state from vsphere

### Actual Behavior

* module.prometheus-dev-server.vsphere_virtual_machine.prometheus: vsphere_virtual_machine.prometheus: Get unexpected status code: 500: call failed: Error response from vCloud Suite API: {"value":{"messages":[{"id":"vapi.bindings.method.impl.unexpected","default_message":"Provider method implementation threw unexpected exception: Rejecting login on a session where login failed","args":["Rejecting login on a session where login failed"]}]},"type":"com.vmware.vapi.std.errors.internal_server_error"}

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I've restarted the `VMWare vSphere Web Client` service on the vCenter host and this didn't seem to have any effect.

**Comment by johnjelinek** [comment]
Seems maybe my sessions from the vsphere provider may not be getting closed? https://communities.vmware.com/thread/569440

**Comment by johnjelinek** [comment]
Confirmed: on an error (like this one), the session are not being closed. I can see a huge list of sessions piled up in the vCenter.

**Comment by johnjelinek** [comment]
I also tried restarting the VMWare vAPI Endpoint, didn't fix it.

**Comment by johnjelinek** [comment]
Here's what I see in the `vapi` logs:
```
2018-05-31T11:48:23.125-05:00 | INFO  | sso2                      | SecurityContextUtil            | Acquired act-as token from STS valid until 5/31/18 11:51 AM with renewable flag of true
2018-05-31T11:48:23.388-05:00 | INFO  | sso2                      | BaseSessionImpl                | Created session is valid until 6/1/18 11:48 AM
2018-05-31T11:48:23.390-05:00 | INFO  | sso2                      | MasterSessionManagerImpl       | Created session johnjelinek (internal id ab15f870-cba3-48e2-a401-0a3f53aa16e5, token b53fc...) 
2018-05-31T11:48:24.102-05:00 | WARN  | vAPI-I/O dispatcher-0     | SessionApiSecurityUtil         | Failed to create child session with session manager com.vmware.cis.tagging.sessions.session_manager for session johnjelinek (internal id ab15f870-cba3-48e2-a401-0a3f53aa16e5, token b53fc...).
com.vmware.vapi.std.errors.internal_server_error => {data=<unset>, messages=[com.vmware.vapi.std.localizable_message => {id=vapi.bindings.method.impl.unexpected, default_message=Provider method implementation threw unexpected exception: Rejecting login on a session where login failed, args=[Rejecting login on a session where login failed]}]}
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil.onLoginResult(SessionApiSecurityUtil.java:248)
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil.access$500(SessionApiSecurityUtil.java:43)
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil$2.setResult(SessionApiSecurityUtil.java:230)
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil$2.setResult(SessionApiSecurityUtil.java:220)
	at com.vmware.vapi.endpoint.session.SessionFacade$1.setResult(SessionFacade.java:108)
	at com.vmware.vapi.endpoint.session.SessionFacade$1.setResult(SessionFacade.java:90)
	at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider$ResponseCallbackImpl.received(JsonApiProvider.java:221)
	at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider$1.received(JsonApiProvider.java:249)
	at com.vmware.vapi.internal.protocol.client.rpc.http.ApacheHttpAsyncClientTransport$SingleResponseConsumer.responseCompleted(ApacheHttpAsyncClientTransport.java:454)
	at com.vmware.vapi.internal.protocol.client.rpc.http.ApacheHttpAsyncClientTransport$DecoratorConsumer.responseCompleted(ApacheHttpAsyncClientTransport.java:318)
	at org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:418)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:164)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:355)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:242)
	at org.apache.http.impl.nio.client.LoggingAsyncRequestExecutor.inputReady(LoggingAsyncRequestExecutor.java:87)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:264)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:73)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:37)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:584)
	at java.lang.Thread.run(Thread.java:745)
2018-05-31T11:49:18.200-05:00 | INFO  | sso4                      | SecurityContextUtil            | Acquired act-as token from STS valid until 5/31/18 11:52 AM with renewable flag of true
2018-05-31T11:49:18.462-05:00 | INFO  | sso4                      | BaseSessionImpl                | Created session is valid until 6/1/18 11:49 AM
2018-05-31T11:49:18.462-05:00 | INFO  | sso4                      | MasterSessionManagerImpl       | Created session johnjelinek (internal id a2a1f8fd-bb02-47c7-b0df-39d91e7c63d2, token 2c75e...) 
2018-05-31T11:49:19.259-05:00 | WARN  | vAPI-I/O dispatcher-1     | SessionApiSecurityUtil         | Failed to create child session with session manager com.vmware.cis.tagging.sessions.session_manager for session johnjelinek (internal id a2a1f8fd-bb02-47c7-b0df-39d91e7c63d2, token 2c75e...).
com.vmware.vapi.std.errors.internal_server_error => {data=<unset>, messages=[com.vmware.vapi.std.localizable_message => {id=vapi.bindings.method.impl.unexpected, default_message=Provider method implementation threw unexpected exception: Rejecting login on a session where login failed, args=[Rejecting login on a session where login failed]}]}
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil.onLoginResult(SessionApiSecurityUtil.java:248)
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil.access$500(SessionApiSecurityUtil.java:43)
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil$2.setResult(SessionApiSecurityUtil.java:230)
	at com.vmware.vapi.endpoint.auth.impl.SessionApiSecurityUtil$2.setResult(SessionApiSecurityUtil.java:220)
	at com.vmware.vapi.endpoint.session.SessionFacade$1.setResult(SessionFacade.java:108)
	at com.vmware.vapi.endpoint.session.SessionFacade$1.setResult(SessionFacade.java:90)
	at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider$ResponseCallbackImpl.received(JsonApiProvider.java:221)
	at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider$1.received(JsonApiProvider.java:249)
	at com.vmware.vapi.internal.protocol.client.rpc.http.ApacheHttpAsyncClientTransport$SingleResponseConsumer.responseCompleted(ApacheHttpAsyncClientTransport.java:454)
	at com.vmware.vapi.internal.protocol.client.rpc.http.ApacheHttpAsyncClientTransport$DecoratorConsumer.responseCompleted(ApacheHttpAsyncClientTransport.java:318)
	at org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:418)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:164)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:355)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:242)
	at org.apache.http.impl.nio.client.LoggingAsyncRequestExecutor.inputReady(LoggingAsyncRequestExecutor.java:87)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:264)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:73)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:37)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:584)
	at java.lang.Thread.run(Thread.java:745)
2018-05-31T11:49:53.828-05:00 | INFO  | state-manager1            | DefaultStateManager            | Creating runtime state context.
2018-05-31T11:49:53.829-05:00 | INFO  | state-manager1            | DynamicSSLIOSessionStrategy    | Reconfiguring trusted certificates.
2018-05-31T11:49:53.862-05:00 | INFO  | state-manager1            | DynamicSSLIOSessionStrategy    | Found 1 trusted certificates.
```

**Comment by johnjelinek** [comment]
This is vCenter 6.0.0, 2776511 and ESXi 6.0.0, 3029758

**Comment by johnjelinek** [comment]
Another note: I can login with these credentials using the vSphere Client with no issues.

**Comment by bill-rich** [comment]
Hi @johnjelinek! Looks like you're probably running into the session limit and then the new attempts are getting rejected. If you set `persist_session` to `true` in your provider configuration, the same session will be used until it expires, which should resolve your issue.
