### ISSUE TITLE
vSphere authentication issue after vSphere upgrade

### ISSUE THREAD

**Issue by lawrence-c** [terraform-providers/terraform-provider-vsphere#777]
We recently upgraded our vSphere instance from 6.5 to VMware ESXi, 6.7.0, 13006603, and have been hitting an authentication issue. Occasionally it works, but most of the time it just fails. Any ideas how I can debug this further?

### Terraform Version
```
Terraform v0.11.13
+ provider.null v2.1.2
+ provider.vsphere v1.10.0
```

### Terraform Configuration Files

```hcl
provider "vsphere" {
    version                 = "1.10.0"
    vsphere_server          = "${var.vsphere_vcenter}"
    user                    = "${var.vsphere_user}"
    password                = "${var.vsphere_password}"
    allow_unverified_ssl    = true
}
data "vsphere_datastore" "datastore" {
    name          = "${var.vsphere_datastore}"
    datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
    name          = "Production/Resources"
    datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
    name          = "VM Network"
    datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
    name          = "${var.vm_template}"
    datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
    name                = "${var.vm_name}"
    folder              = "${var.vm_folder}"
    resource_pool_id    = "${data.vsphere_resource_pool.pool.id}"
    datastore_id        = "${data.vsphere_datastore.datastore.id}"

    num_cpus            = "${var.vm_cpu}"
    memory              = "${var.vm_ram}"
    guest_id            = "${data.vsphere_virtual_machine.template.guest_id}"
    scsi_type           = "${data.vsphere_virtual_machine.template.scsi_type}"

    wait_for_guest_net_timeout = 10

    network_interface {
        network_id      = "${data.vsphere_network.network.id}"
        adapter_type    = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
    }

    disk {
        label            = "disk0"
        size             = "${var.vm_disk_size}"
        eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
        thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
    }

    clone {
        template_uuid   = "${data.vsphere_virtual_machine.template.id}"
    }
}
```

### Debug Output
Various errors when running `terraform plan`
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error refreshing state: 2 error(s) occurred:

* module.build-vm-01.provider.vsphere: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
* module.build-vm-02.provider.vsphere: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_network.network: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_network.network: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.build-vm-02.provider.vsphere: Error connecting to CIS REST endpoint: Login failed: body: {"type":"com.vmware.vapi.std.errors.unauthenticated","value":{"messages":[{"args":[],"default_message":"Authentication required.","id":"com.vmware.vapi.endpoint.method.authentication.required"}]}}, status: 401 Unauthorized
```

```
Error: Error running plan: 2 error(s) occurred:

* module.build-vm-01.provider.vsphere: error setting up new vSphere SOAP client: Post https://srv-vc001.uhad.com/sdk: dial tcp: lookup srv-vc001.uhad.com on 8.8.8.8:53: no such host
* module.build-vm-02.provider.vsphere: error setting up new vSphere SOAP client: Post https://srv-vc001.uhad.com/sdk: dial tcp: lookup srv-vc001.uhad.com on 8.8.8.8:53: no such host
```

### Steps to Reproduce

1. `terraform plan`

### References
- GH-375
- GH-756

**Comment by bill-rich** [comment]
Hi @lawrence-c! It looks like the issue is at least partly related to DNS issues. How recently was the upgrade run, and did the host name change at all? I'd recommend doing a few DNS lookups from where you are running Terraform from to make sure you are consistently able to resolve the host name. 

Are the credentials you are using in Terraform working when logging in through the web UI? If so, please  try using [govc](https://github.com/vmware/govmomi/tree/master/govc) to find out if the failure is consistent through the API. Another useful tool for debugging is the DEBUG log. It may not be super useful since the failure is in authentication, but it is a good place to start.

**Comment by lawrence-c** [comment]
Hi @bill-rich, thank you for the response!

The upgrade was last week, and the hostname has somewhat changed (according to VCenters UI):
```
DNS Name:	srv-vc001
DNS Name:	SRV-VC001.uhad.com
``` 
Although I don't see this being an issue as the reference in the terraform files has always been `uh-srv-vc001.uhad.com`, and there wasn't an issue before.

I've used macOS's built in Network Utility and that can resolve the given hostname just fine.

I've installed `govc` and ran the following without issue:
```
export GOVC_URL="srv-vc001.uhad.com"
export GOVC_USERNAME=""
export GOVC_PASSWORD=""
govc ls
```
Adding `TF_LOG=DEBUG` in the `terraform` commands just confirms the authentication error issue just a bit more wordy. EG:
```
* module.build-vm-02.provider.vsphere: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
2019-06-06T11:08:41.678+0100 [DEBUG] plugin.terraform-provider-null_v2.1.2_x4: 2019/06/06 11:08:41 [ERR] plugin: plugin server: accept unix /var/folders/g1/4cm_xpk1373bc_4v30x6jqn00000gp/T/plugin726407364: use of closed network connection
2019-06-06T11:08:41.678+0100 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/06/06 11:08:41 [ERR] plugin: plugin server: accept unix /var/folders/g1/4cm_xpk1373bc_4v30x6jqn00000gp/T/plugin720961846: use of closed network connection
2019-06-06T11:08:41.678+0100 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/06/06 11:08:41 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-06-06T11:08:41.678+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.10.0_x4: 2019/06/06 11:08:41 [ERR] plugin: plugin server: accept unix /var/folders/g1/4cm_xpk1373bc_4v30x6jqn00000gp/T/plugin225107385: use of closed network connection
* module.build-vm-01.provider.vsphere: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

Is there anything else I can try?

**Comment by bill-rich** [comment]
Are you using `persist_session`? It is possible you are running into an issue with a saved session. When a session expires, a new one should be created. Just to make sure, can you please try deleting any saved sessions in `${HOME}/.govmomi/sessions`? 

If you log into the vCenter server and take a look at the vCenter events, is there any additional information about the authentication error?

**Comment by lawrence-c** [comment]
I'm not using `persist_session` as an argument in the `govc` command if that's what you mean? I've removed `~/.govmomi/sessions`, and `govc ls` is working fine (tested this a few times).

I've also updated the terraform with:
```
provider "vsphere" {
    version                 = "1.10.0"
    vsphere_server          = "${var.vsphere_vcenter}"
    user                    = "${var.vsphere_user}"
    password                = "${var.vsphere_password}"
    allow_unverified_ssl    = true
    persist_session         = false
}
```
However I'm still getting the authentication issue...

---

Logging into the vCenter server, some various logs when spamming `terraform plan`:

`/var/log/auth.log` is empty.

`/var/log/vmware/vapi/endpoint/endpoint.log`:
```
com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Invalid credentials Please see the server log to find more detail regarding exact cause of the failure.
	at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:116)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.doInvoke(DispatchImpl.java:259)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.invoke(DispatchImpl.java:289)
	at com.vmware.vim.sso.client.impl.SoapBindingImpl.sendMessage(SoapBindingImpl.java:161)
	at com.vmware.vim.sso.client.impl.SoapBindingImpl.sendMessage(SoapBindingImpl.java:114)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.sendRequest(SecurityTokenServiceImpl.java:927)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.executeRoundtrip(SecurityTokenServiceImpl.java:856)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl.acquireToken(SecurityTokenServiceImpl.java:144)
	at com.vmware.vapi.endpoint.sso.context.StsFacadeImpl.acquireToken(StsFacadeImpl.java:129)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil$3.run(SecurityContextUtil.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-07T08:13:02.931Z | INFO  | sso3                      | SecurityContextUtil            | Failed to acquire SAML token.
com.vmware.vapi.endpoint.sso.StsException: com.vmware.vim.sso.client.exception.AuthenticationFailedException: Provided credentials are not valid.
	at com.vmware.vapi.endpoint.sso.context.StsFacadeImpl.acquireToken(StsFacadeImpl.java:155)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil$3.run(SecurityContextUtil.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.vmware.vim.sso.client.exception.AuthenticationFailedException: Provided credentials are not valid.
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.handleFaultCondition(SecurityTokenServiceImpl.java:996)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.sendRequest(SecurityTokenServiceImpl.java:932)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.executeRoundtrip(SecurityTokenServiceImpl.java:856)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl.acquireToken(SecurityTokenServiceImpl.java:144)
	at com.vmware.vapi.endpoint.sso.context.StsFacadeImpl.acquireToken(StsFacadeImpl.java:129)
	... 4 more
2019-06-07T08:13:02.931Z | INFO  | sso3                      | BaseSessionImpl                | Cannot authenticate user login request com.vmware.vapi.security.UserPassSecurityContext@2389f344 with error com.vmware.vapi.endpoint.sso.StsException: com.vmware.vim.sso.client.exception.AuthenticationFailedException: Provided credentials are not valid..
```
---
`/var/log/vmware/vpxd/vpxd.log`:
```
2019-06-07T08:25:02.563Z info vpxd[44150] [Originator@6876 sub=vpxLro opID=5bf8fffb] [VpxLRO] -- BEGIN lro-2552537 -- ServiceInstance -- vim.ServiceInstance.retrieveContent -- 525b981c-25be-ae0b-bd9f-725308a95239
2019-06-07T08:25:02.563Z info vpxd[44150] [Originator@6876 sub=vpxLro opID=5bf8fffb] [VpxLRO] -- FINISH lro-2552537
2019-06-07T08:25:02.564Z info vpxd[44062] [Originator@6876 sub=vpxLro opID=386de6e9] [VpxLRO] -- BEGIN lro-2552538 -- ServiceInstance -- vim.ServiceInstance.retrieveContent -- 52b146b3-9e9e-f0b7-a3a2-db5b3c34cf45
2019-06-07T08:25:02.564Z info vpxd[44062] [Originator@6876 sub=vpxLro opID=386de6e9] [VpxLRO] -- FINISH lro-2552538
2019-06-07T08:25:02.566Z info vpxd[43940] [Originator@6876 sub=vpxLro opID=3752e7f0] [VpxLRO] -- BEGIN lro-2552539 -- SessionManager -- vim.SessionManager.login -- 5242d756-aca7-a91f-b500-7cb1534fc136
2019-06-07T08:25:02.567Z info vpxd[43846] [Originator@6876 sub=vpxLro opID=23f959f0] [VpxLRO] -- BEGIN lro-2552540 -- SessionManager -- vim.SessionManager.login -- 52b02292-4183-fdce-65be-e40bd6a918d4
2019-06-07T08:25:02.580Z error vpxd[43846] [Originator@6876 sub=[SSO] opID=23f959f0] [UserDirectorySso] AcquireToken exception: N9SsoClient27InvalidCredentialsExceptionE(Authentication failed: Invalid credentials)
--> [context]zKq7AVECAAAAAJwe0AAVdnB4ZAAAoPMqbGlidm1hY29yZS5zbwAAiCAbALyaGAFrSQJsaWJzc29jbGllbnQuc28AAbZNAgHGUgIB61MCAboRAgJME/V2cHhkAAKQIJ4C6TOfg0SrAQFsaWJ2aW0tdHlwZXMuc28AApWIcgLgjHECkZpxAjj1cQAxYiMA+mQjAF1JKwTUcwBsaWJwdGhyZWFkLnNvLjAABb2ODmxpYmMuc28uNgA=[/context]
2019-06-07T08:25:02.581Z error vpxd[43846] [Originator@6876 sub=User opID=23f959f0] Failed to authenticate user <username>
2019-06-07T08:25:02.586Z error vpxd[43940] [Originator@6876 sub=[SSO] opID=3752e7f0] [UserDirectorySso] AcquireToken exception: N9SsoClient27InvalidCredentialsExceptionE(Authentication failed: Invalid credentials)
--> [context]zKq7AVECAAAAAJwe0AAVdnB4ZAAAoPMqbGlidm1hY29yZS5zbwAAiCAbALyaGAFrSQJsaWJzc29jbGllbnQuc28AAbZNAgHGUgIB61MCAboRAgJME/V2cHhkAAKQIJ4C6TOfg0SrAQFsaWJ2aW0tdHlwZXMuc28AApWIcgLgjHECkZpxAjj1cQAxYiMA+mQjAF1JKwTUcwBsaWJwdGhyZWFkLnNvLjAABb2ODmxpYmMuc28uNgA=[/context]
2019-06-07T08:25:02.587Z error vpxd[43940] [Originator@6876 sub=User opID=3752e7f0] Failed to authenticate user <username>
2019-06-07T08:25:05.588Z info vpxd[43940] [Originator@6876 sub=vpxLro opID=3752e7f0] [VpxLRO] -- FINISH lro-2552539
2019-06-07T08:25:05.588Z info vpxd[43940] [Originator@6876 sub=Default opID=3752e7f0] [VpxLRO] -- ERROR lro-2552539 -- SessionManager -- vim.SessionManager.login: vim.fault.InvalidLogin:
--> Result:
--> (vim.fault.InvalidLogin) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = <unset>
-->    msg = ""
--> }
--> Args:
-->
--> Arg userName:
--> "<username>"
--> Arg password:
--> (not shown)
-->
--> Arg locale:
--> "en_US"
2019-06-07T08:25:07.581Z info vpxd[43846] [Originator@6876 sub=vpxLro opID=23f959f0] [VpxLRO] -- FINISH lro-2552540
2019-06-07T08:25:07.581Z info vpxd[43846] [Originator@6876 sub=Default opID=23f959f0] [VpxLRO] -- ERROR lro-2552540 -- SessionManager -- vim.SessionManager.login: vim.fault.InvalidLogin:
--> Result:
--> (vim.fault.InvalidLogin) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = <unset>
-->    msg = ""
--> }
--> Args:
-->
--> Arg userName:
--> "<username>"
--> Arg password:
--> (not shown)
-->
--> Arg locale:
--> "en_US"
2019-06-07T08:25:11.042Z info vpxd[43934] [Originator@6876 sub=vpxLro opID=sps-Main-713498-950-25] [VpxLRO] -- BEGIN lro-2552542 -- ServiceInstance -- vim.ServiceInstance.retrieveContent -- 526ededf-2020-844a-8de7-640d0a41fe0c
2019-06-07T08:25:11.042Z info vpxd[43934] [Originator@6876 sub=vpxLro opID=sps-Main-713498-950-25] [VpxLRO] -- FINISH lro-2552542
2019-06-07T08:25:11.049Z info vpxd[28627] [Originator@6876 sub=vpxLro opID=sps-Main-713498-950-59] [VpxLRO] -- BEGIN lro-2552544 -- AuthorizationManager -- vim.AuthorizationManager.hasPrivilegeOnEntities -- 52a53e77-8f12-dfb2-bca0-df57fd1ea847(52b1459a-5b31-0889-2066-7a8d13339a47)
2019-06-07T08:25:11.050Z info vpxd[28627] [Originator@6876 sub=vpxLro opID=sps-Main-713498-950-59] [VpxLRO] -- FINISH lro-2552544
```
---
Using the Events view in the vSphere Client does show the correct information when I get an authentication error in `terraform`, something along the lines of:
```
Description:
    07/06/2019, 09:53:32
    Cannot login <username>@<ip address>
Event Type Description:
    A user attempted to log in with an unknown or invalid username
Possible Causes:
    The username is unknown to the system Action: If you are using Active Directory, check the health of the domain controller
    The user provided an invalid password Action: Supply the correct password
Related events:
    There are no related events.
```
I'm currently looking at the domain controllers and will see if anything is up with them..

I'm also curious if there needs to be a patch/fix which needs to be installed onto the ESXi hosts?

**Comment by bill-rich** [comment]
Thanks for the additional logs and config information. I do not know of any vSphere patches that are needed, but it may be worth looking at known issues on your current version. 

The strange part is that it works sometimes. If it never worked, I'd suspect there was an issue in how the username or password is being handled in the provider. It is even more strange that it works consistently with govc since they are both using the same govmomi library.

Can you give an estimate on how often you are able to establish a connection using Terraform?

**Comment by lawrence-c** [comment]
Well, the connection just broke whenever running `terraform plan` or `apply`, but if I run it enough times, eventually it would successfully run (not idea for CI!).

I believe that this is an internal DNS issue, but I haven't gotten to the root of it. We've currently worked around it by creating a `bot.local` account on the vsphere platform and are using that instead.

Going to close this for now, but thank you for the help! Will add additional comments if I find the root cause...

**Comment by zilmarr** [comment]
I don't know if it's ok to comment here since this issue is closed, but I had a similar problem.
What solved for me is that I needed to use user@domain as username, like `terraform@vsphere.local`.
