### ISSUE TITLE
Terraform crash with  "error: code = Unavailable desc = transport" is closing and "panic: reflect.Value.Addr of unaddressable value"

### ISSUE THREAD

**Issue by sofixa** [terraform-providers/terraform-provider-vsphere#914]
### Terraform Version
terraform 0.12.16

### vSphere Provider Version

- Downloading plugin for provider "aws" (hashicorp/aws) 2.15.0...
- Downloading plugin for provider "vsphere" (hashicorp/vsphere) 1.13.0...
- Downloading plugin for provider "vault" (hashicorp/vault) 2.0.0...

### Affected Resource(s)

- `vsphere_virtual_machine`, maybe more

### Terraform Configuration Files

```hcl
```terraform
resource "vsphere_virtual_machine" "pa2-wwwpp" {
  count            = var.pa2-wwwpp_count
  provider         = vsphere.pa2
  name             = "${var.client}.${var.wwwpp_project}.${var.wwwpp_instance}${count.index + 1 + var.pa2-wwwpp_count-offset}"
  guest_id         = data.vsphere_virtual_machine.pa2_template9.guest_id
  resource_pool_id = data.vsphere_resource_pool.pa2_pool.id
  datastore_id     = data.vsphere_datastore.pa2_datastore_01.id
  folder           = var.client

  num_cpus = var.wwwpp_num-cpus
  memory   = var.wwwpp_memory * 1024

  network_interface {
    network_id   = data.vsphere_network.pa2_adm.id
    adapter_type = var.network_interface_type
  }

  network_interface {
    network_id   = data.vsphere_network.pa2_frontpp.id
    adapter_type = var.network_interface_type
  }

  network_interface {
    network_id   = data.vsphere_network.pa2_backpp.id
    adapter_type = var.network_interface_type
  }

  disk {
    label            = "disk0.vmdk"
    size             = var.wwwpp_disk-size
    eagerly_scrub    = var.eagerly_scrub
    thin_provisioned = var.thin_provisioned
  }

  lifecycle {
    ignore_changes = [clone[0].template_uuid,disk[0]]
  }

  cpu_hot_add_enabled        = true
  memory_hot_add_enabled     = true
  wait_for_guest_net_timeout = 0

  clone {
    template_uuid = data.vsphere_virtual_machine.pa2_template9.id
  }

  extra_config = {
    "guestinfo.vmname" = "${var.client}.${var.wwwpp_project}.${var.wwwpp_instance}${count.index + 1 + var.pa2-wwwpp_count-offset}"
  }
}

```terraform
variable "client" {
  default = "test"
}

variable "network_interface_type" {
  default = "vmxnet3"
}

variable "guest_id" {
  default = "debian9Guest"
}

variable "scsi_type" {
  default = "lsilogic"
}

variable "eagerly_scrub" {
  default = true
}

variable "thin_provisioned" {
  default = false
}

```

### vCenter version
6.7U2

### Debug Output
https://gist.github.com/sofixa/1ecd99df10ae9061a1e844a7f89f2214

### vCenter log
/var/log/vmware/vapi/endpoint/endpoint.log

```
2019-11-28T16:54:35.777Z | ERROR | vcenter-shim-activity-5   | ActivityFutureResultCallback   | Activity threw exception.
com.vmware.vapi.std.errors.Unauthenticated: Unauthenticated (com.vmware.vapi.std.errors.unauthenticated) => {
    messages = [LocalizableMessage (com.vmware.vapi.std.localizable_message) => {
    id = com.vmware.api.vcenter.unauthenticated,
    defaultMessage = Authentication required.,
    args = []
}],
    data = <null>
}
        at com.vmware.vsphereshim.lib.ErrorLib.createUnauthenticated(ErrorLib.java:40)
        at com.vmware.vsphereshim.lib.ErrorLib.createUnauthenticated(ErrorLib.java:44)
        at com.vmware.vsphereshim.impl.cis.session.SessionDeleteActivity.getVapiErrorForLogout(SessionDeleteActivity.java:92)
        at com.vmware.vsphereshim.impl.cis.session.SessionDeleteActivity.phaseOnLogout(SessionDeleteActivity.java:86)
        at sun.reflect.GeneratedMethodAccessor614942.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vmware.activity.toolkit.simple.executor.SimpleActivityWorker.executePhase(SimpleActivityWorker.java:362)
        at com.vmware.activity.toolkit.simple.executor.SimpleActivityWorker.executeActivity(SimpleActivityWorker.java:244)
        at com.vmware.activity.toolkit.simple.executor.SimpleActivityWorker.run(SimpleActivityWorker.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- GH-869
- GH-777
- GH-904

**Comment by sofixa** [comment]
1.14 came out and it's fixed, so i'm closing this issue.
